const panels = {
  setup: document.getElementById("setupPanel"),
  login: document.getElementById("loginPanel"),
  settings: document.getElementById("settingsPanel"),
  message: document.getElementById("messagePanel"),
};

const forms = {
  setup: document.getElementById("setupForm"),
  login: document.getElementById("loginForm"),
  settings: document.getElementById("settingsFormAdmin"),
};

const messageText = document.getElementById("messageText");
const sessionText = document.getElementById("sessionText");
const tokenHint = document.getElementById("tokenHint");
const logoutButton = document.getElementById("logoutButton");
const zabbixUrlButton = document.getElementById("zabbixUrlButton");
const ZABBIX_URL_TEMPLATE = "http://DIGITE-O-IP-DO-ZABBIX/zabbix/api_jsonrpc.php";
const nextUrl = new URLSearchParams(window.location.search).get("next");

function showPanel(name) {
  Object.entries(panels).forEach(([key, panel]) => {
    if (key !== "message") panel.hidden = key !== name;
  });
}

function showMessage(message, type = "info") {
  panels.message.hidden = false;
  panels.message.dataset.type = type;
  messageText.textContent = message;
}

function clearMessage() {
  panels.message.hidden = true;
  messageText.textContent = "";
}

async function api(path, options = {}) {
  const { headers = {}, ...requestOptions } = options;
  const response = await fetch(path, {
    credentials: "same-origin",
    ...requestOptions,
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      ...headers,
    },
  });
  const data = await response.json().catch(() => ({}));

  if (!response.ok || data.ok === false) {
    throw new Error(data.error || `HTTP ${response.status}`);
  }

  return data;
}

async function submitForm(event, action) {
  event.preventDefault();
  clearMessage();
  const submitButton = event.submitter;
  if (submitButton) submitButton.disabled = true;

  try {
    await action();
  } catch (error) {
    showMessage(error.message, "error");
  } finally {
    if (submitButton) submitButton.disabled = false;
  }
}

function formJson(form) {
  return Object.fromEntries(new FormData(form).entries());
}

function idsToText(ids) {
  return Array.isArray(ids) ? ids.join(", ") : "";
}

function textToIds(value) {
  return String(value || "")
    .split(",")
    .map(item => item.trim())
    .filter(Boolean);
}

function getSafeNextUrl() {
  if (!nextUrl) return "";

  try {
    // Accept only same-origin destinations generated by the dashboard guard.
    const url = new URL(nextUrl, window.location.href);
    if (url.origin !== window.location.origin) return "";
    if (url.pathname.endsWith("/admin.html")) return "";
    return url.href;
  } catch {
    return "";
  }
}

function redirectAfterLogin() {
  const destination = getSafeNextUrl();
  if (!destination) return false;

  window.location.href = destination;
  return true;
}

function focusZabbixUrlTemplate() {
  const input = forms.settings.zabbix_api_url;
  if (!input.value.trim()) {
    input.value = ZABBIX_URL_TEMPLATE;
  }

  input.focus();
  const tokenStart = input.value.indexOf("DIGITE-O-IP-DO-ZABBIX");
  if (tokenStart >= 0) {
    input.setSelectionRange(tokenStart, tokenStart + "DIGITE-O-IP-DO-ZABBIX".length);
    return;
  }

  input.select();
}

async function loadSession() {
  clearMessage();

  try {
    const session = await api("api/auth.php");

    if (session.needsSetup) {
      showPanel("setup");
      return;
    }

    if (!session.user) {
      showPanel("login");
      return;
    }

    if (redirectAfterLogin()) return;

    sessionText.textContent = `Logado como ${session.user.name || session.user.username}`;
    showPanel("settings");
    await loadSettings();
  } catch (error) {
    showPanel("login");
    showMessage(error.message, "error");
  }
}

async function loadSettings() {
  const data = await api("api/settings.php");
  const settings = data.settings;
  const form = forms.settings;

  form.zabbix_api_url.value = settings.zabbix_api_url || ZABBIX_URL_TEMPLATE;
  form.zabbix_token.value = "";
  form.refresh_seconds.value = settings.refresh_seconds || 10;
  form.api_limit.value = settings.api_limit || 500;
  form.page_interval_seconds.value = settings.page_interval_seconds || 15;
  form.sort_mode.value = settings.sort_mode || "recent";
  form.fetch_mode.value = settings.fetch_mode || "incidents";
  form.monitored_group_ids.value = idsToText(settings.monitored_group_ids);
  form.monitored_host_ids.value = idsToText(settings.monitored_host_ids);
  tokenHint.textContent = settings.has_zabbix_token
    ? "Token ja salvo. Preencha apenas se quiser substituir."
    : "Nenhum token salvo.";

  if (data.usingExampleConfig) {
    showMessage("Crie config/app.php a partir de config/app.example.php e troque o app_key antes de usar em producao.", "warning");
  }
}

forms.setup.addEventListener("submit", event => {
  submitForm(event, async () => {
    await api("api/auth.php", {
      method: "POST",
      body: JSON.stringify({ ...formJson(forms.setup), setup: true }),
    });
    showMessage("Administrador criado com sucesso.", "success");
    window.history.replaceState(null, "", "admin.html");
    await loadSession();
  });
});

forms.login.addEventListener("submit", event => {
  submitForm(event, async () => {
    await api("api/auth.php", {
      method: "POST",
      body: JSON.stringify(formJson(forms.login)),
    });
    if (redirectAfterLogin()) return;
    await loadSession();
  });
});

forms.settings.addEventListener("submit", event => {
  submitForm(event, async () => {
    const payload = formJson(forms.settings);
    payload.monitored_group_ids = textToIds(payload.monitored_group_ids);
    payload.monitored_host_ids = textToIds(payload.monitored_host_ids);

    if (String(payload.zabbix_api_url || "").includes("DIGITE-O-IP-DO-ZABBIX")) {
      showMessage("Substitua o modelo pelo IP ou DNS real do Zabbix antes de salvar.", "error");
      focusZabbixUrlTemplate();
      return;
    }

    await api("api/settings.php", {
      method: "POST",
      body: JSON.stringify(payload),
    });
    showMessage("Configuracoes salvas.", "success");
    await loadSettings();
  });
});

logoutButton.addEventListener("click", async () => {
  clearMessage();

  try {
    await api("api/auth.php", { method: "DELETE" });
    showPanel("login");
    showMessage("Sessao encerrada.", "success");
  } catch (error) {
    showMessage(error.message, "error");
  }
});

zabbixUrlButton.addEventListener("click", focusZabbixUrlTemplate);

loadSession();
