server {
    listen {{PORT}} default_server;
    listen [::]:{{PORT}} default_server;
    server_name {{SERVER_NAME}};

    root {{INSTALL_DIR}};
    index index.php;

    location = / {
        try_files /index.php =404;
    }

    location = /index.html {
        rewrite ^ /index.php last;
    }

    location = /admin.html {
        rewrite ^ /admin.php last;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:{{PHP_FPM_SOCKET}};
    }

    location ~ ^/(?:backups|config|database|deploy|includes|outputs|work)(?:/|$) {
        deny all;
    }

    location ~ /\. {
        deny all;
    }
}
